version: 2

sources:
  - name: raw_gz
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales data for greenweez company
        # freshness testing
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        freshness: 
          warn_after: {count: 90, period: day}
        columns:
          - name: date_date
            description:  date of purchase
    
        
      - name: product
        identifier: raw_gz_product
        description: products on greenweez
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
              
      - name: ship
        identifier: raw_gz_ship
        description: ship data of greenweez
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique 
              - not_null

      - name: adwords
        identifier: raw_gz_adwords
        description: raw data of adwords
      

      - name: bing
        identifier: raw_gz_bing
        description: raw data of bing
      

      - name: criteo
        identifier: raw_gz_criteo
        description: raw data of criteo


      - name: facebook
        identifier: raw_ga_facebook
        description: raw data of facebook
        
