version: 2

sources:
  - name: raw_gz
    schema: gz_raw_data
    tables: 
      - name: sales
        identifier:  raw_gz_sales
        description: sales data for greenweez company
      - name: product
        identifier: raw_gz_product
        description: products on greenweez
      - name: ship
        identifier: raw_gz_ship
        description: ship data of greenweez






